
services:
  maxi:
    image: meinubuntu
    container_name: ${NAME:-maxi}
    environment:
      - MY_ENV_VAR=${ENV1:-5B-2}   # Setze hier die gewünschte Umgebungsvariable
    volumes:
      - ${DATA}:/testdata
    tty: true
